version: "3.2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    ports:
      - "4000:4000"
    volumes:
      - .:/var/www
  mongo:
    image: mongo:4.1.5
    ports:
      - "27017:27017"
